### ISSUE TITLE
Contraseña en las cookies

### ISSUE THREAD

**Issue by franciscop** [JavierGonzalez/POL#117]
## Problema y solución propuesta

Para mantener a los usuarios logineados entre sesiones se debería de usar un token generado de forma random y guardado con un hash en la base de datos. En específico, me estoy refiriendo al código [de inc-login.php](https://github.com/JavierGonzalez/VirtualPol/blob/master/public_html/inc-login.php) (linea 40):

```
if (md5(CLAVE.$r['pass']) == $_COOKIE['teorizapass'])
```

Que me dió la primera pista sobre lo que se estaba haciendo y al código [de login.php](https://github.com/JavierGonzalez/VirtualPol/blob/master/public_html/registrar/login.php), que es donde se establece la cookie (linea 403):

```
    setcookie('teorizapass', md5(CLAVE.$pass), $expire, '/', USERCOOKIE);
```

Para implementar la función _remember me_, se tiene que generar un token random cada vez que el usuario desee ser recordado. Recomiendo utilizar [`mcrypt_create_iv()`](http://es1.php.net/mcrypt_create_iv), aunque [existen formas todavía más seguras](http://stackoverflow.com/q/1182584/938236), pero no las he probado y por lo tanto no las puedo recomendar.

Una vez hecho esto, se guarda un hash del token ([no el token en sí](http://stackoverflow.com/q/13426710/938236)) en la base de datos con SHA256. Se podría usar bcrypt, pero si se elige un token lo suficientemente largo, este no [sería necesario](http://stackoverflow.com/q/17215401/938236). Por último se guarda el token en la cookie del usuario sin hashear.

Cada usuario debería de tener múltiples tokens para permitirle ser recordado en múltiples dispositivos. No recomiendo reutilizar el token, y cada uno debe de ser reiniciado cada cierto tiempo. Un buen momento sería cuando se comprueba la cookie por primera vez (la autentificación para la misma sesión se haría por $_SESSION).
## Protección en el cliente

La primera parte, utilizar un token generazo de forma aleatoria, tiene que ver con la seguridad en el cliente. Si alguien robara la cookie del usuario podría averiguar su contraseña original. Esto se debe a que yo sé mi contraseña, y por lo tanto puedo deducir `CLAVE` [con la suficiente potencia computacional](http://security.stackexchange.com/a/19908/9161).

Una vez he obtenido `CLAVE`, con obtener la cookie de cualquier usuario puedo hallar otra vez el original del `md5()`, esta vez bastante más fácil (asumiendo que la contraseña del usuario es más _sencilla_ que `CLAVE`). Por estas razones, no hay que enviar de vuelta la contraseña al usuario, sino un token generado al azar.
## Protección del sistema 1

Ahora mismo, si alguien robara la base de datos, podría recuperar la contraseña de la mayoría (todos aquellos con una contraseña que no sea muy compleja) una vez obtenida la CLAVE como se explica en el punto anterior. Esto pone en riesgo no solo la página, sino todas aquellas en las que el usuario usa el mismo username/email y contraseña, que puede ser básicamente toda la identidad del usuario.
## Protección del sistema 2

A parte de la base de datos, el atacante consigue robar la CLAVE. En esa situación sería extremadamente fácil que se recuperen todas las contraseñas.
## Conclusión y otras ventajas

Lo siento por haberlo alargado tanto, pero me parece que es un tema lo suficientemente importante como para explicarlo con detalle.
## Links de interés
- [What is the best way to implement “remember me” for a website?](http://stackoverflow.com/q/244882/938236)
- [hashed passwords in cookies](http://stackoverflow.com/q/11402409/938236).
- [Is Blowfish necessary for security token in PHP remember me system?](http://stackoverflow.com/q/17215401/938236)

**Comment by JavierGonzalez** [comment]
Reabro porque veo valor en esta aportación (6 años despues).

**Comment by franciscop** [comment]
Cierro por falta de actividad
