### ISSUE TITLE
Instalar la plataforma en vps 

### ISSUE THREAD

**Issue by JavierGallego** [JavierGonzalez/POL#137]
Buenos días, soy totalmente nuevo en esto de programar y demás, pero tengo un vps donde voy cargando mis proyectos con cms, me gustaría saber si me pudiérais ayudar a instalar este sistema, he seguido la guía, lpero me pierdo mucho, muchos requisitos, no hay una manera que sea poner la url donde esté cargado y que salte el instalador?

¿Podríais ayudarme a instalarlo? Muchas gracias de antemano.

**Comment by JavierGonzalez** [comment]
Hola!

Hoy he lanzado POL v5.

Es una buena refactorizacion, que simplifica el codigo, el desarrollo y la instalacion.

Ahora ya no hace falta configuracion extra en el Apache, ni multiples sub-dominios.

Ahora, debería funcionar VirtualPol en local mucho más facilmente.

Básicamente la instalacion es como un wordpress. Aunque tendrás que crear la base de datos a mano y configurar su acceso. Eso es lo unico dificil. Por lo demás, es solo poner los archivos en el directorio PHP.

Si encuentras problemas por favor avisame y te ayudaré segun tenga tiempo.

Un saludo y bienvenido!

**Comment by JavierGallego** [comment]
Genial!, muchas gracias, descargo la nueva versión y lo pruebo muchísimas gracias!

**Comment by JavierGallego** [comment]
Por cierto Javier, la guía de instalación está al día?, es que sigo viendo la anterior, si me puedes indicar como es la nueva forma sería genial.

**Comment by JavierGonzalez** [comment]
No he tenido tiempo de llegar a ese nivel.

Pero deberia ser tan facil como poner el codigo en algo como /var/www/, cargar la base de datos con la info SQL que hay en "database" (en toda la refactorizacion NO he cambiado nada en la base de datos) y configurar el usuario y contraseña de la base de datos creando el archivo *passwords.php (quitando .template).

Con eso, deberias tenerlo funcionando.

Por favor, intentalo y comentame las dudas.

**Comment by JavierGonzalez** [comment]
He cambiado `*passwords.php` por `*passwords.ini`

**Comment by JavierGonzalez** [comment]
Resuelto por @bradduk en https://github.com/JavierGonzalez/POL/pull/142
