### ISSUE TITLE
Imposible clonar el proyecto en windows

### ISSUE THREAD

**Issue by bradduk** [JavierGonzalez/POL#138]
Los directorio que empiezan con un asterisco (*) hacen que sea imposible clonar, o más bien extraer, el proyecto en windows.

**Comment by Shrewd** [comment]
Añado : 

warning: the following paths have collided (e.g. case-sensitive paths
on a case-insensitive filesystem) and only one from the same
colliding group is in the working tree:

  'img/banderas/Plebiscito.png'
  'img/banderas/plebiscito.png'

**Comment by JavierGonzalez** [comment]
@Shrewd arreglado! https://github.com/JavierGonzalez/POL/commit/ee35c7ef32e075f3b55ea25d84d289d9a21fe21b

**Comment by JavierGonzalez** [comment]
Es aceptable que no pueda funcionar en Windows? (ya funciona el docker)

**Comment by JavierGonzalez** [comment]
@bradduk Arreglado! https://github.com/JavierGonzalez/POL/commit/62e59e4192cd09e9b90b198cf8f09a946ec95388
