### ISSUE TITLE
Links rotos en emails de votaciones

### ISSUE THREAD

**Issue by Logatto** [JavierGonzalez/POL#154]
Despues del refactor en la versión 5.0 del proyecto, se removieron muchos links que tenian concatenados el DOMINIO, y esos enlaces funcionan correctamente al navegar por la Web, pero cuando esos href se envian por email, en email no agrega el dominio de VP.

![image](https://user-images.githubusercontent.com/1206969/93946621-57e97880-fcff-11ea-9ad6-512d549f7894.png)

**Comment by JavierGonzalez** [comment]
Bienvenido, gracias!!!
