### ISSUE TITLE
Cuentas multipersonales

### ISSUE THREAD

**Issue by CyberTheo** [JavierGonzalez/POL#163]
El usuario Lector sugiere una nueva feature para desarrollar en el futuro. Me parece extremadamente interesante así que la copio aquí, para que se tenga en cuenta.

La idea sería desarrollar **cuentas multipersonales**, con más de un titular. También creo que sería interesante y útil valorar la posibilidad de **ceder cuentas bancarias a otros usuarios.**

**Comment by Shrewd** [comment]
La opción sencilla es : 
**En vez de multi-titular, sea la posibilidad de tener autorizados que tengan acceso a la cuenta.
Y la opción de ceder cuenta (traspaso de titular) a otro ciudadano.**

O se puede ir mas allá... ya que a mi me hubiese gustado hacerlo mas parecido a la VR, tu realmente pides una cuenta a un banco, y es el banco el que te impone las condiciones, creando competencia y posibilidad de elección frente a comisiones, etc.

Añadimos un privilegio para ver quien puede crear cuentas, añadiendo así la posibilidad de que cualquier ciudadano pueda crear cuentas, o sean las empresas quienes lo hagan. 
El impuesto por crear cuentas nuevas sigue teniendo sentido, bien se cobra al ciudadano o bien la empresa, quedando esta como propietaria (titular)

Se podrían añadir autorizados, que tendrían acceso para operar con ella, con la exención de impuestos podría ser la empresa la que cobrase por tener la cuenta (gracias a las transacciones automáticas) o bien el gobierno (impuestos) o crear incluso impuestos para empresas de algún tipo concreto.

**Comment by bradduk** [comment]
Buenas, este fin de semana, cuando he podido, he avanzado algo en esta issue. De momento lo que he hecho es crear una nueva tabla para relacionar las cuentas con los apoderados que tiene y que cualquiera que esté en la lista de apoderados pueda operar como si fuera el dueño.

Voy a incluir ahora lo de poder ceder las cuentas y las empresas y me gustaría además incluir que se puedan realizar pagos directamente desde las cuentas. 

@Shrewd tu opción de crear un nuevo privilegio me parece cojonuda, pero sinceramente, yo no me atrevo a meterme en el nucleo acceso ese, si te animas tienes todo mi apoyo moral :D

**Comment by Shrewd** [comment]
Privilegio en BD, falta en acceso : |crear_cuenta;ciudadanos:
