### ISSUE TITLE
Bugs Arquitecto

### ISSUE THREAD

**Issue by Onii-Chan9** [JavierGonzalez/POL#196]
Hay varios bugs del panel de Arquitecto :

1. El arquitecto no puede acceder al menu de editar sus parcelas. Esto quiere decir que no puede cambiar el nombre a las parcelas ni el color.

2. Cuando fusionas parcelas que son propias del usuario funciona pero te redirige al menu de parcelas del Estado. No se si este bug ocurre solo si eres Arquitecto/Presidente o si a las personas que no tengan acceso al panel les redirigira a esa pagina

3. El sistema de poner colores hexadecimales (no se si lo son) introduciendo texto, no eligiendo de la drop down sino escribiendo numero-letra-numero, no funciona bien. Elijo unas letras que ya estan presentes en otra parcela y no me deja. Es muy raro porque no siempre ocurre. Intentare replicarlo más veces.
--

**Comment by aledegrazia** [comment]
Amigos!! No me bajan de la conversa!! GRACIAS!!!
