### ISSUE TITLE
No cambia el nick

### ISSUE THREAD

**Issue by Onii-Chan9** [JavierGonzalez/POL#199]
Como me lo dijeron lo digo

Intentan cambiar el nick y no les deja, aparece un mensaje diciendo que sigan las reglas o algo parecido
Yo no puedo probarlo.

**Comment by Shrewd** [comment]
Hablando con el usuario afectado, lo ha intentado de nuevo y ha funcionado
En principio se utiliza una expresión regular para comprobar el formato

[A-Za-z0-9_]{3,14}

https://github.com/JavierGonzalez/POL/blob/c330f16a61a8f7705ed5531d5017d709d8ff700b/registrar/login/panel.php#L105

También he preguntado por el navegador, Firefox, el mensaje parece distinto en cada navegador.
Un misterio mas...

**Comment by bradduk** [comment]
Finalmente creo que se ha podido cambiar el usuario, no se si estaba usando algún carácter chungo o que...
