### ISSUE TITLE
Error en proceso

### ISSUE THREAD

**Issue by bradduk** [JavierGonzalez/POL#229]
Buenas @JavierGonzalez  no se si estos mensajes los ves, pero no veo otra forma de contactar contigo :(

No se si sabrás que no está funcionando bien el proceso, desde hace un par de semanas no se eligen los nuevos SC y ayer no se lanzaron las elecciones automáticas. Entiendo que el problema debe estar relacionado con alguno de los últimos commits que hiciste para actualizar el framework pero no veo una relación clara la verdad. En mi entorno en local el proceso está funcionando correctamente así que no puedo depurar mucho más allá de que funciona todo hasta, presumiblemente, la parte del impuesto de empresas. ¿Podrias ehcar un ojo a los logs a ver que puede estar pasando?

A parte de eso, ¿Verías factible darme acceso a ver los logs para en el futuro poder ayudarte con estas situaciones? Entiendo que en los logs no hay nada de información sensible que pueda causar problemas...

**Comment by Shrewd** [comment]
Yo te acabo de leer, Intentaré investigarlo y/o avisarle yo...

**Comment by bradduk** [comment]
Mil gracias @Shrewd , perdona que no te mencionara, pensé que solo Gonzo tenía acceso a los logs.

Las elecciones las lancé "manualmente" yo al final, pero el proceso sigue fallando en algún punto indeterminado....
